const $ = s => document.querySelector(s);
const app = { tab:'dashboard', data:{}, edit:null };
const labels={produtos:'Produtos',categorias:'Categorias',banners:'Banners',empresa:'Minha Empresa',tema:'Tema',seo:'SEO',config:'Configurações',publicacao:'Publicação'};
async function loadAll(){ app.data={ produtos:await ProdutoService.listar({todos:true}), categorias:await CategoriaService.listar(), banners:await BannerService.listar(), empresa:await EmpresaService.obter(), tema:await TemaService.obter(), seo:await SeoService.obter(), config:await ConfigService.obter()}; render(); }
function nav(tab){ app.tab=tab; app.edit=null; render(); }
function pending(){return DataStore.getChanges().filter(c=>c.status==='PENDENTE')}
function shell(content){ const plano=app.data.config?.plano||{}; return `<aside class="admin-sidebar"><h1>Admin</h1>${['dashboard','empresa','produtos','categorias','banners','tema','seo','config','publicacao'].map(t=>`<button class="${app.tab===t?'active':''}" onclick="nav('${t}')">${labels[t]||'Dashboard'}</button>`).join('')}</aside><main class="admin-content"><header><h2>${labels[app.tab]||'Dashboard'}</h2><span class="pill">Plano ${plano.tipo||'START'}</span></header>${content}</main>${pending().length?`<div class="publish-bar">Você possui alterações não publicadas. <button onclick="nav('publicacao')">Revisar</button><button onclick="nav('publicacao')">Publicar</button></div>`:''}`}
function render(){ let html=''; if(app.tab==='dashboard') html=dashboard(); if(app.tab==='empresa') html=empresa(); if(app.tab==='produtos') html=produtos(); if(app.tab==='categorias') html=categorias(); if(app.tab==='banners') html=banners(); if(app.tab==='tema') html=tema(); if(app.tab==='seo') html=seo(); if(app.tab==='config') html=config(); if(app.tab==='publicacao') html=publicacao(); $('#adminApp').innerHTML=shell(html); }
function dashboard(){return `<section class="grid cards"><div><b>${app.data.produtos.length}</b><span>Produtos cadastrados</span></div><div><b>${app.data.categorias.length}</b><span>Categorias</span></div><div><b>${app.data.banners.length}</b><span>Banners</span></div><div><b>${pending().length}</b><span>Alterações pendentes</span></div></section><section class="panel"><h3>Últimas alterações</h3>${changesList()}</section>`}
function changesList(){ const c=pending(); return c.length?`<ul>${c.map(x=>`<li><strong>${x.arquivo}</strong> — ${x.tipo} — ${x.horario}</li>`).join('')}</ul>`:'<p>Nenhuma alteração pendente.</p>'; }
function input(k,v='',type='text'){return `<label>${k}<input name="${k}" type="${type}" value="${String(v??'').replaceAll('"','&quot;')}"></label>`}
function textarea(k,v=''){return `<label>${k}<textarea name="${k}">${String(v??'')}</textarea></label>`}
function formObj(sel){return Object.fromEntries(new FormData($(sel)).entries())}
async function saveEmpresa(){ await EmpresaService.salvar(formObj('#fEmpresa')); await loadAll(); }
function empresa(){ const e=app.data.empresa; return `<section class="panel"><form id="fEmpresa" class="form-grid">${['logo','nome','telefone','whatsapp','instagram','facebook','email','endereco','cidade','estado','cep','googleMaps','horario'].map(k=>input(k,e[k]||'')).join('')}${textarea('descricao',e.descricao||'')}<button type="button" onclick="saveEmpresa()">Salvar empresa</button></form></section>`}
function produtos(){ const list=app.data.produtos; return `<section class="panel"><button onclick="editProduto()">Novo produto</button><div class="table">${list.map(p=>`<article><img src="../${p.imagem||''}" onerror="this.style.display='none'"><div><strong>${p.nome}</strong><small>${p.categoria||''} · R$ ${Number(p.preco||0).toFixed(2)} ${p.ativo===false?'· Arquivado':''}</small></div><button onclick="editProduto(${p.id})">Editar</button><button onclick="dupProduto(${p.id})">Duplicar</button><button onclick="arcProduto(${p.id})">Arquivar</button><button onclick="delProduto(${p.id})">Excluir</button></article>`).join('')}</div></section>${app.edit?.tipo==='produto'?produtoForm(app.edit.item):''}`}
function produtoForm(p={}){return `<section class="panel modalish"><form id="fProduto" class="form-grid">${input('id',p.id||'','hidden')}${input('nome',p.nome||'')}${select('categoria',app.data.categorias.map(c=>c.nome),p.categoria)}${input('preco',p.preco||0,'number')}${input('precoPromocional',p.precoPromocional||'','number')}${textarea('descricao',p.descricao||'')}${input('imagem',p.imagem||'')}${input('galeria',(p.galeria||p.imagens||[]).join(', '))}${input('codigo',p.codigo||'')}${check('destaque',p.destaque)}${check('novo',p.novo)}${check('promocao',p.promocao)}${check('ativo',p.ativo!==false)}${input('ordem',p.ordem||0,'number')}<button type="button" onclick="saveProduto()">Salvar produto</button></form></section>`}
function select(k,opts,val=''){return `<label>${k}<select name="${k}">${opts.map(o=>`<option ${o===val?'selected':''}>${o}</option>`).join('')}</select></label>`}
function check(k,v){return `<label class="check"><input name="${k}" type="checkbox" ${v?'checked':''}> ${k}</label>`}
function editProduto(id){ const item=id?app.data.produtos.find(p=>String(p.id)===String(id)):{}; app.edit={tipo:'produto',item}; render(); }
async function saveProduto(){ const f=formObj('#fProduto'); f.id=f.id?Number(f.id):undefined; f.preco=Number(f.preco||0); f.precoPromocional=f.precoPromocional?Number(f.precoPromocional):null; f.galeria=f.galeria.split(',').map(s=>s.trim()).filter(Boolean); ['destaque','novo','promocao','ativo'].forEach(k=>f[k]=!!$(`#fProduto [name=${k}]`)?.checked); f.ordem=Number(f.ordem||0); await ProdutoService.salvar(f); await loadAll(); }
async function dupProduto(id){await ProdutoService.duplicar(id); await loadAll()} async function arcProduto(id){await ProdutoService.arquivar(id); await loadAll()} async function delProduto(id){if(confirm('Excluir?')){await ProdutoService.excluir(id); await loadAll()}}
function genericList(file,fields){ const list=app.data[file]; return `<section class="panel"><button onclick="editGeneric('${file}')">Novo</button><div class="table">${list.map(x=>`<article><div><strong>${x.nome||x.titulo||x.id}</strong><small>${Object.entries(x).filter(([k])=>fields.includes(k)).map(([k,v])=>`${k}: ${v}`).join(' · ')}</small></div><button onclick="editGeneric('${file}',${x.id})">Editar</button><button onclick="delGeneric('${file}',${x.id})">Excluir</button></article>`).join('')}</div></section>${app.edit?.tipo===file?genericForm(file,fields,app.edit.item):''}`}
function genericForm(file,fields,item={}){return `<section class="panel modalish"><form id="fGeneric" class="form-grid">${input('id',item.id||'','hidden')}${fields.map(k=>typeof item[k]==='boolean'?check(k,item[k]):input(k,item[k]||'', k==='ordem'?'number':'text')).join('')}<button type="button" onclick="saveGeneric('${file}')">Salvar</button></form></section>`}
function categorias(){return genericList('categorias',['nome','icone','ordem','ativa'])} function banners(){return genericList('banners',['titulo','subtitulo','imagem','botao','link','ativo','ordem'])}
function editGeneric(file,id){app.edit={tipo:file,item:id?app.data[file].find(x=>String(x.id)===String(id)): {}}; render()} async function saveGeneric(file){const f=formObj('#fGeneric'); f.id=f.id?Number(f.id):undefined; ['ativa','ativo'].forEach(k=>{if($(`#fGeneric [name=${k}]`))f[k]=$(`#fGeneric [name=${k}]`).checked}); if(f.ordem)f.ordem=Number(f.ordem); await ({categorias:CategoriaService,banners:BannerService}[file]).salvar(f); await loadAll()} async function delGeneric(file,id){await ({categorias:CategoriaService,banners:BannerService}[file]).excluir(id); await loadAll()}
async function saveSingle(file,svc){await svc.salvar(formObj('#fSingle')); await loadAll()} function single(file,svc,fields){const o=app.data[file]; return `<section class="panel"><form id="fSingle" class="form-grid">${fields.map(k=>typeof o[k]==='boolean'?check(k,o[k]):textarea(k,o[k]||'')).join('')}<button type="button" onclick="saveSingle('${file}', ${svc})">Salvar</button></form></section>`}
function tema(){const t=app.data.tema; return `<section class="panel"><form id="fSingle" class="form-grid">${input('corPrimaria',t.corPrimaria,'color')}${input('corSecundaria',t.corSecundaria,'color')}${input('fonte',t.fonte)}${input('botoes',t.botoes)}${input('layout',t.layout)}${check('modoEscuro',t.modoEscuro)}<button type="button" onclick="saveTema()">Salvar tema</button></form></section>`} async function saveTema(){const f=formObj('#fSingle'); f.modoEscuro=$('#fSingle [name=modoEscuro]').checked; await TemaService.salvar(f); await loadAll()}
function seo(){const s=app.data.seo; return `<section class="panel"><form id="fSingle" class="form-grid">${input('titulo',s.titulo)}${textarea('descricao',s.descricao)}${input('keywords',s.keywords)}${input('imagemCompartilhamento',s.imagemCompartilhamento)}<button type="button" onclick="saveSingleSeo()">Salvar SEO</button></form></section>`} async function saveSingleSeo(){await SeoService.salvar(formObj('#fSingle')); await loadAll()}
function config(){const p=app.data.config.plano||{}; return `<section class="panel"><form id="fConfig" class="form-grid">${input('tipo',p.tipo)}${['limiteProdutos','limiteCategorias','limiteBanners','limiteAlteracoes'].map(k=>input(k,p[k], 'number')).join('')}${['permitePromocao','permiteSEO','permiteTema'].map(k=>check(k,p[k])).join('')}<button type="button" onclick="saveConfig()">Salvar plano</button></form></section>`} async function saveConfig(){const f=formObj('#fConfig'); ['limiteProdutos','limiteCategorias','limiteBanners','limiteAlteracoes'].forEach(k=>f[k]=Number(f[k]||0)); ['permitePromocao','permiteSEO','permiteTema'].forEach(k=>f[k]=$(`#fConfig [name=${k}]`).checked); await ConfigService.salvar({...app.data.config, plano:f}); await loadAll()}
async function validatePub(){const errors=await PublicacaoService.validar(); $('#pubErrors').innerHTML=errors.length?`<div class="errors"><b>Publicação bloqueada</b><ul>${errors.map(e=>`<li>${e}</li>`).join('')}</ul></div>`:'<div class="ok">Validação aprovada.</div>'; return errors;}
async function genPackage(){const errors=await validatePub(); if(errors.length) return; const pacote=await PublicacaoService.pacote(); $('#packageOut').value=JSON.stringify(pacote,null,2);}
async function mailPackage(){await genPackage(); const body=encodeURIComponent($('#packageOut').value); location.href=`mailto:${app.data.empresa.email||''}?subject=${encodeURIComponent('Pacote de publicação')}&body=${body}`;}
function publicacao(){return `<section class="panel"><h3>Revisão</h3>${changesList()}<button onclick="validatePub()">Validar</button><button onclick="genPackage()">Gerar pacote</button><button onclick="mailPackage()">Abrir e-mail</button><button onclick="PublicacaoService.limparPublicados(); loadAll()">Limpar rascunhos publicados</button><div id="pubErrors"></div><textarea id="packageOut" rows="14" placeholder="Pacote de publicação"></textarea></section>`}
loadAll();
